services:
  # Action Server Service
  - type: web
    name: expobeton-actions
    env: docker
    dockerfilePath: ./Dockerfile.actions
    plan: free
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false
    healthCheckPath: /health
    
  # Rasa Server Service
  - type: web
    name: expobeton-rasa
    env: docker
    dockerfilePath: ./Dockerfile.rasa
    plan: free
    envVars:
      - key: RASA_MODEL
        value: /app/models/expobeton-french.tar.gz
      - key: ACTION_ENDPOINT_URL
        value: https://expobeton-actions.onrender.com/webhook
      - key: RASA_PRO_LICENSE
        value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwODk0MDJjOS00NDIyLTQ5MzktYjc5OC0zYjdmMWEwM2MzNmUiLCJpYXQiOjE3NjEzOTY1MDIsIm5iZiI6MTc2MTM5NjUwMCwic2NvcGUiOiJyYXNhOnBybyByYXNhOnBybzpjaGFtcGlvbiByYXNhOnZvaWNlIiwiZXhwIjoxODU2MDkwOTAwLCJlbWFpbCI6ImJvdEBleHBvYmV0b25yZGMuY29tIiwiY29tcGFueSI6IlJhc2EgQ2hhbXBpb25zIn0.yMrH3Z4cMDR13sj79yqiVhUohkRqgfE4iwYt81-vJlzGEy-KRE7bSuvMP5_mX5aBSF0Mtl_a0g8D2wfiKUA8o_4Q92Hvd7jB393GdS1bzs2gr0b44IgHm2sxXP3QzWtOI_iXGqdI-N_7vu1zpcfK8ig_nKYGMFqJ4LT9rnAeFU9OjwV70LReStA-kQ7Oo_TypRb_vzOXE647rxmFDO1OeTxR_1nYaBgdV-FsWP8_MNkX8dYNDtVwgP1cebZGYfvKbo0yneU1xhLbl4ztumMjcNzjC_ptr1HQ-nXJdvSSwJifpkhD_8ukYxWPFeG7tYJrayON6VtpxpPgKTFdEb67PQ
    healthCheckPath: /
    
  # Static Web Service (for chat widget)
  - type: web
    name: expobeton-web
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./web
    routes:
      - type: rewrite
        source: /webhooks/rest/webhook
        destination: https://expobeton-rasa.onrender.com/webhooks/rest/webhook
