apiVersion: v1
kind: Secret
metadata:
  name: expobeton-secrets
type: Opaque
data:
  # Ces valeurs doivent être encodées en base64
  # echo -n 'votre_valeur' | base64
  cohere-api-key: Y29oZXJlLWFwaS1rZXkK  # Remplacer par votre clé encodée
  smtp-username: c210cC11c2VybmFtZQo=  # Remplacer par votre nom d'utilisateur encodé
  smtp-password: c210cC1wYXNzd29yZAo=  # Remplacer par votre mot de passe encodé
  notification-email: bm90aWZpY2F0aW9uLWVtYWlsCg==  # Remplacer par votre email encodé