apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ExpoBeton Chatbot</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>Bienvenue sur le chatbot ExpoBeton</h1>
        <div id="chat-container"></div>
        <script>
            // Code du widget de chat
            console.log("Chat widget loaded");
        </script>
    </body>
    </html>