apiVersion: v2
name: expobeton-chatbot
description: A Helm chart for ExpoBeton Rasa Chatbot
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled