# Default values for expobeton-chatbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro
  tag: "3.10.27"
  pullPolicy: IfNotPresent

rasa:
  service:
    type: LoadBalancer
    port: 5005
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

actions:
  service:
    type: ClusterIP
    port: 5055
  resources: {}

web:
  service:
    type: LoadBalancer
    port: 80
  resources: {}

postgresql:
  enabled: false
  postgresqlUsername: expobeton
  postgresqlPassword: changeme
  postgresqlDatabase: expobeton
  service:
    port: 5432

# Secrets must be provided
secrets:
  # cohereApiKey: base64-encoded-key
  # smtpUsername: base64-encoded-username
  # smtpPassword: base64-encoded-password
  # notificationEmail: base64-encoded-email